### ISSUE TITLE
Cannot pass array of maps to SpecBuilder.withData

### ISSUE THREAD

**Issue by bearnshaw** [aishfenton/Vegas#26]
I'm using vegas 0.2.3 with scala 2.10 in an Apache Toree notebook, and it appears that I can't pass an array of maps to `withData`.  For example:

```scala
(Vegas().withData(
    Array(Map("id" -> 0, "val" -> 10.1),
          Map("id" -> 1, "val" -> 9.2))
    )
    .encodeX("id", Nominal)
    .encodeY("val", Quantitative)
    .mark(Bar).show)
```

gives the error:

```scala
Name: Compile Error
Message: <console>:93: error: overloaded method value withData with alternatives:
  (url: String,formatType: vegas.spec.FormatType)vegas.DSL.SpecBuilder <and>
  (values: Map[String,Any]*)vegas.DSL.SpecBuilder
 cannot be applied to (Array[scala.collection.immutable.Map[String,AnyVal]])
              (Vegas().withData(
                       ^
```

I tried using tupled, but I get the same overloaded method error.  Obviously, for the small example I've shown here I can just get rid of the wrapping Array, but in general I want to programmatically supply data to `withData`.  Is there a way to do this?

BTW, I can see from the README that I can recompile spark and get a `withData` method on RDDs and DataFrames, and this would solve my problem, but in my spark environment I'm stuck with scala 2.10 at the moment, which I think means I can't get a version of Vegas higher than 2.11.

**Comment by bearnshaw** [comment]
Nevermind, conversion of array to var-args using `:_*` syntax works (as explained [here](http://stackoverflow.com/questions/31064753/how-to-pass-scala-array-into-scala-vararg-method)).  So, if `a` is an array of maps, then the following works:

```scala
val a = Array(Map("id" -> 0, "val" -> 10.1), Map("id" -> 1, "val" -> 9.2))
(Vegas().withData(a:_*)
    .encodeX("id", Nominal)
    .encodeY("val", Quantitative)
    .mark(Bar).show)
```

Thanks @aishfenton for the great library!

**Comment by aishfenton** [comment]
No prob. We're working on a big backend refactor for it, but almost finished now. Then we'll focus on few more front-end things to make the scala API easier.

**Comment by bearnshaw** [comment]
Sounds good @aishfenton, looking forward to it.

Question - How do I sort an axis?  I can't figure out how to get that option in, e.g., `encodeX`.

**Comment by aishfenton** [comment]
Sorry for slow reply. That's coming shortly. We hadn't yet implemented the sort stuff in vega-lite, but new approach #34 will be adding them.
