### ISSUE TITLE
Implement Basic Flink Support and Write Unit Tests

### ISSUE THREAD

**Issue by ASRagab** [aishfenton/Vegas#38]
In addition to Spark I'd like to also be able to use Apache Flink, I have a PR sitting that POCs this possibility. It would work quite similarly to the spark integration (i.e. pass it a FlinkDataSet and a case class/or anything that extends Product with Serializable).

**Comment by aishfenton** [comment]
Great! Would love to support Flink. If you send through the PR we'll incorporate it.

We just merged a fairly big change (all the Json serialization parts are now code generated). I don't think it'll change anything in the areas you mention, but mentioning just in case.

**Comment by ASRagab** [comment]
Ah great. I'll take a look at the change and try to get a PR to you soon.

**Comment by aishfenton** [comment]
Merged.
